# Generated by Django 2.2.10 on 2020-11-04 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанр',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movie/actors/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Биография')),
                ('career', models.CharField(max_length=100, verbose_name='Карьера')),
                ('gender', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=15, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-updated'],
                'unique_together': {('name', 'birth_date', 'birth_place')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Оригинальное название')),
                ('ru_title', models.CharField(max_length=70, verbose_name='Название на русском')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Краткое содержание')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('age_limit', models.CharField(blank=True, default='0+', max_length=10, null=True, verbose_name='Возрастное ограничение')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie/posters/', verbose_name='Постер')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fullness', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Полнота содержания')),
                ('cast', models.ManyToManyField(blank=True, related_name='movie_cast', to='films.Person', verbose_name='Актерский совстав')),
                ('directors', models.ManyToManyField(blank=True, related_name='movie_director', to='films.Person', verbose_name='Режиссер')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='films.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-updated'],
                'unique_together': {('orig_title', 'ru_title', 'release_date')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название колекции')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie/collections/', verbose_name='Изображение')),
                ('followers', models.ManyToManyField(blank=True, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Последователи')),
                ('movies', models.ManyToManyField(related_name='collections', to='films.Movie', verbose_name='Фильмы')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='GenreTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='films.Genre')),
            ],
            options={
                'verbose_name': 'Жанр Translation',
                'db_table': 'films_genre_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
    ]
