# Generated by Django 2.2.10 on 2020-05-15 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movie/actors/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография')),
                ('career', models.CharField(max_length=100, verbose_name='Карьера')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=50, verbose_name='Место рождения')),
                ('film_nums', models.PositiveIntegerField(verbose_name='Количество работ')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_title', models.CharField(max_length=100, verbose_name='Оригинальное название')),
                ('ru_title', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000, verbose_name='Краткое содержание')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('age_limit', models.PositiveIntegerField(verbose_name='Возрастное ограничение')),
                ('tagline', models.CharField(max_length=200, verbose_name='Слоган')),
                ('imdb_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie/posters/', verbose_name='Постер')),
                ('cast', models.ManyToManyField(blank=True, related_name='film_cast', to='films.People', verbose_name='Актерский совстав')),
                ('director', models.ManyToManyField(blank=True, related_name='film_director', to='films.People', verbose_name='Режиссер')),
                ('genre', models.ManyToManyField(blank=True, related_name='films', to='films.Genre', verbose_name='Жанр')),
            ],
        ),
    ]
