# Generated by Django 2.2.10 on 2020-11-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='MovieTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3, verbose_name='Языковой код')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Краткое содержание')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie/posters/', verbose_name='Постер')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='films.Movie', verbose_name='Фильм')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ru_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
    ]
