# Generated by Django 2.2.10 on 2020-05-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-release_date'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанр'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-film_nums'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
