# Generated by Django 2.2.10 on 2020-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20200515_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='orig_title',
            field=models.CharField(max_length=50, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='ru_title',
            field=models.CharField(max_length=50, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название колекции')),
                ('film', models.ManyToManyField(related_name='collections', to='films.Film', verbose_name='Фильм')),
            ],
        ),
    ]
