# Generated by Django 2.2.10 on 2020-11-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20201107_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movietranslations',
            options={'ordering': ['movie'], 'verbose_name': 'Первеводы фильма', 'verbose_name_plural': 'Первеводы фильмов'},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('orig_title', 'release_date')},
        ),
        migrations.AlterUniqueTogether(
            name='movietranslations',
            unique_together={('movie', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='career',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.CreateModel(
            name='PersonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('slug', models.SlugField(unique=True)),
                ('career', models.CharField(max_length=100, verbose_name='Карьера')),
                ('gender', models.CharField(blank=True, max_length=15, null=True, verbose_name='Пол')),
                ('biography', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Биография')),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='films.Person')),
            ],
            options={
                'verbose_name': 'Человек Translation',
                'db_table': 'films_person_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
    ]
