# Generated by Django 2.2.10 on 2020-05-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0003_auto_20200520_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='film',
        ),
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='films',
            field=models.ManyToManyField(related_name='collections', to='films.Film', verbose_name='Фильмы'),
        ),
        migrations.AddField(
            model_name='collection',
            name='followers',
            field=models.ManyToManyField(related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Последователи'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
