# Generated by Django 2.2.10 on 2020-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20200520_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['created'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
