# Generated by Django 2.2.10 on 2020-11-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20201113_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonTranslation',
        ),
    ]
