# Generated by Django 2.2.10 on 2020-11-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_delete_persontranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('slug', models.SlugField()),
                ('career', models.CharField(max_length=100, verbose_name='Карьера')),
                ('gender', models.CharField(blank=True, max_length=15, null=True, verbose_name='Пол')),
                ('biography', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Биография')),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='films.Person')),
            ],
            options={
                'verbose_name': 'Человек Translation',
                'db_table': 'films_person_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
    ]
