# Generated by Django 2.2.10 on 2020-05-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20200520_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='people',
            name='film_nums',
        ),
    ]
