# Generated by Django 2.2.10 on 2020-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20200520_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default=None, upload_to='movie/posters/', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
