# Generated by Django 2.2.10 on 2020-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20200520_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='people',
            name='biography',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Биография'),
        ),
    ]
