# Generated by Django 2.2.10 on 2020-05-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20200520_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-updated'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-updated'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
