# Generated by Django 2.2.10 on 2020-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20200520_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/collections/', verbose_name='Изображение'),
        ),
    ]
