# Generated by Django 2.2.10 on 2020-05-21 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Последователи'),
        ),
    ]
