# Generated by Django 2.2.10 on 2020-06-15 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_auto_20200521_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_title', models.CharField(max_length=50, verbose_name='Оригинальное название')),
                ('ru_title', models.CharField(max_length=50, verbose_name='Название на русском')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое содержание')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('age_limit', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('poster', models.ImageField(upload_to='movie/posters/', verbose_name='Постер')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cast', models.ManyToManyField(blank=True, related_name='movie_cast', to='films.People', verbose_name='Актерский совстав')),
                ('directors', models.ManyToManyField(blank=True, related_name='movie_director', to='films.People', verbose_name='Режиссер')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='films.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-updated'],
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='films',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collections', to='films.Movie', verbose_name='Фильмы'),
        ),
    ]
