# Generated by Django 2.2.10 on 2020-06-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20200615_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-id'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
