# Generated by Django 2.2.10 on 2020-06-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_auto_20200617_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-updated'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-updated'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('orig_title', 'ru_title', 'release_date')},
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together={('name', 'birth_date', 'birth_place')},
        ),
    ]
