# Generated by Django 2.2.10 on 2020-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_auto_20200619_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(default=0, max_length=10, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='orig_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Оригинальное название'),
        ),
    ]
