# Generated by Django 2.2.10 on 2020-10-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_auto_20201028_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
