# Generated by Django 2.2.10 on 2020-10-28 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_auto_20201028_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг IMDB'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ru_title',
            field=models.CharField(max_length=70, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
    ]
