# Generated by Django 2.2.10 on 2020-10-28 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_auto_20201028_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fullness',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Длительность'),
        ),
    ]
