# Generated by Django 2.2.10 on 2020-10-28 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_auto_20201029_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movie_cast', through='films.Acting', to='films.Person', verbose_name='Актерский совстав'),
        ),
    ]
