# Generated by Django 2.2.10 on 2020-10-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_auto_20201029_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acting',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Роль'),
        ),
    ]
