# Generated by Django 2.2.10 on 2020-10-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_auto_20201029_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('NONE', None), ('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='NONE', max_length=15, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fullness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Полнота содержания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения'),
        ),
    ]
