# Generated by Django 2.2.10 on 2020-10-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_auto_20201030_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=15, null=True, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='Acting',
        ),
    ]
