# Generated by Django 2.2.10 on 2020-10-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0031_auto_20201030_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movie_cast', to='films.Person', verbose_name='Актерский совстав'),
        ),
    ]
